### PR TITLE
Refactoring and restructuring the project

### PR DESCRIPTION
**Pull request by joumenharzli**
Great project ;)

### CODE REVIEW

**Review by heiyukidev — COMMENTED** [review]
i really appreciate the contribution and the restructuring of the project, I didn't find time to properly do it myself.

**Comment by heiyukidev** [comment]
I've adjusted the structure a little bit because the module is already in production so changing the main entry point of the project to 'dist/hyResources.min.js' will cause a breaking change. I want to maintaint the actual structure not to hurt other developpers projects. Thank you for the contribution

**Comment by heiyukidev** [comment]
i also published the module on NPM so its now available on Yarn with the correct dependecies, thank you again

**Comment by joumenharzli** [comment]
No problem it's your project do what you want

**Pull request merged**
